### ISSUE TITLE
The prerelases published on each PR merge don't match the future version

### ISSUE THREAD

**Issue by pygy** [JAForbes/pr-release#345]
In Mithril, the [release PR](https://github.com/MithrilJS/mithril.js/pull/2776) has already beeen bumped to `v3.0.0`.

However, the prereleases over at [npm](https://www.npmjs.com/package/mithril?activeTab=versions) are based off `v2.2.3`. This seems wrong...

**Comment by JAForbes** [comment]
Yeah interesting, I'll take a look

**Comment by JAForbes** [comment]
An oversight on my part, mithril having a default branch of master (instead of main) requires --target to be explicitly set.

**Comment by pygy** [comment]
Yes, thanks for the fix :-)
