### ISSUE TITLE
While juggling release channels, how do we ensure the change log ends up in the right repo?

### ISSUE THREAD

**Issue by pygy** [JAForbes/pr-release#347]
I'm dabbling with pr-release, GH actions and the docs build script over at https://github.com/pygy/dummy-gummy.

Is there something in place to have the change logs of the legacy branches (`v1-next` => `v1-release`) added to the main `release` branch?

**Comment by JAForbes** [comment]
Haha love the name!  There isn't, but sounds like a good idea.   I don't think it should be built in as this could be solved a variety of ways but maybe some simple scripting could work.  But if there's some simple / elegant way to do this in core let me know, it just seems like it could be project specific.

Few ideas:
- You can run extract-changelog with a different --target / --source and then redirect `changelog.md` in to the real changelog file.  Maybe as a custom CI job like 'update-changelog', but wouldn't be idemptotent.

- I'm sort of partial to keeping them in separate files on separate branches and concatenating them when building the website on the latest release channel (e.g. v3 in mithril's case).  It may actually be clearer to keep them separate and only combine them on the website.  It's pretty easy to curl the changelog from a different branch, or use octokit's get object, or even `git show branch:filename`.

**Comment by JAForbes** [comment]
Closing in favour of #348, I'll document different recommendations.  Please post here or there with whatever ideas you have or approach you take.
