### ISSUE TITLE
Default branch naming scheme

### ISSUE THREAD

**Issue by pygy** [JAForbes/pr-release#349]
I think it would be better, by default, to treat `main` as the dev branch, and to have `release` as a secondary, dedicated branch.

It could help with adoption because it would reduce installation friction since it meshes well with git and GH defaults.

**Comment by JAForbes** [comment]
I think this encourages changes staying in development for too long.  In my mind main = production.  But it would be cool to have a mode or a documented recipe that supports this approach.  But as a default I really think merging to main should be a production release, and releasing often should not be a big event.  Making the default branch the release branch encourages a faster release tempo.
